### PR TITLE
add proxy_protocol_v2 support for fnat.

### PR DESCRIPTION
**Pull request by helloliupan**
'proxy_protocol' keyword should be configured in 'keepalived.conf', and virtual_server should be configured with FNAT for TCP, the detailed configurations are as follows:
1. 'global_defs': proxy_protocol_v2 support is available for all virtual_server when 'proxy_protocol' is configured in 'global_defs' block:
global_defs {
        ......
        proxy_protocol
        ......
}

2. 'virtual_server': proxy_protocol_v2 support is available for the given virtual_server when 'proxy_protocol' is configured in 'virtual_server' block:
virtual_server ip_addr port {
        ........
        lb_kind FNAT
        protocol TCP
        proxy_protocol
        ........
}

### CODE REVIEW

**Comment by ywc689** [comment]
Could you explain the use cases and the implementation idea in brief?   I think TOA can be used for the same purpose.

**Comment by ywc689** [comment]
DPVS delivers source IP/port  to backends by TOA. Proxy protocol do almost the same thing in another way. It's suggested that this feature should be enabled by a macro (such as "CONFIG_PROXY_PROTOCOL_V2") defined in "src/config.mk" so that it wouldn't cause overhead for  the one who don't need this feature.

**Comment by donghaobo** [comment]
seems that PP retrans is not considered

**Comment by helloliupan** [comment]
> DPVS delivers source IP/port to backends by TOA. Proxy protocol do almost the same thing in another way. It's suggested that this feature should be enabled by a macro (such as "CONFIG_PROXY_PROTOCOL_V2") defined in "src/config.mk" so that it wouldn't cause overhead for the one who don't need this feature.

thanks for you suggestion. Proxy protocol(PP) has some advantageses over TOA as follow:
1. PP can deliver source IP/Port and dest IP/Port to real servers with both IPv4 and IPv6 condition, while TOA can not fill both source and dest addrs with IPv6 situation;
2. PP is an application layer protocol, we do not need to adapt different kernel versions if the real servers support PP at the same while, nginx for example(https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/).

**Comment by helloliupan** [comment]
> seems that PP retrans is not considered

Right, the retrans for first packet of application layer from client may pass to real servers without PP header, I will fix this later.

**Comment by donghaobo** [comment]
> Right, the retrans for first packet of application layer from client may pass to real servers without PP header, I will fix this later.

if pp header pkt lost, the connection will retry until uplayer close.
client will retrans first payload again and again,  server will ack -PP_LEN again and again.

**Comment by ywc689** [comment]
#923 is the full implementation for proxy protocol in DPVS.

**Pull request closed without merging**
