### PR TITLE
fix the mlx5 config not work

### PR DESCRIPTION
**Pull request by legend050709**
fix the bug of CONFIG_MLX5=y in config.mk not work;

### CODE REVIEW

**Comment by ywc689** [comment]
This bug in introduced by PR #667 . You could fixed it by exchanging the order of `include $(SRCDIR)/dpdk.mk` and `include $(SRCDIR)/config.mk` in src/Makefile.

**Comment by legend050709** [comment]
> This bug is introduced by PR #667 . You could fixed it by exchanging the order of `include $(SRCDIR)/dpdk.mk` and `include $(SRCDIR)/config.mk` in src/Makefile.

**Comment by legend050709** [comment]
> This bug is introduced by PR #667 . You could fixed it by exchanging the order of `include $(SRCDIR)/dpdk.mk` and `include $(SRCDIR)/config.mk` in src/Makefile.

Well, the $(RTE_SDK)/mk/rte.vars.mk included in dpdk.mk overrides CFLAGS, so we need to include dpdk.mk first. 
see the comment in [pr-667](https://github.com/iqiyi/dpvs/pull/667)

**Comment by ywc689** [comment]
It's good practice to keep the dpdk make configs within the "src/dpdk.mk" file.  A more reasonable solution is to move the `include $(RTE_SDK)/mk/rte.vars.mk ` line  in "src/dpdk.mk" into "src/Makefile", in which placing it before all `include` statements.

**Comment by ywc689** [comment]
Because the bug priority is high. I'v make another pr #686 to fix it. You can help review it. Thank you!

**Comment by ywc689** [comment]
Fixed in pr #686 .

**Pull request closed without merging**
