### PR TITLE
ipvs: create dpvs connection pool module.

### PR DESCRIPTION
**Pull request by andrewhit**

### CODE REVIEW

**Comment by azura27** [comment]
@andrewhit 
Hi， when reproducing this PR, the compiling is stopped for depencies ERROR, could you pls take some time to RE-compile this PR  and provide the system info, Thanks a lot~~ the compiling Error are showed below:
The comiling is done on the branch "dpvs-bug-17" of your repository
{/usr/include/bits/socket_type.h:51:0: note: this is the location of the previous definition
 #define SOCK_CLOEXEC SOCK_CLOEXEC
 ^
scheduler.c: In function ‘report_child_status’:
scheduler.c:472:54: error: ‘PACKAGE_VERSION’ undeclared (first use in this function)
    log_message(LOG_INFO, "  Source version %s %s%s", PACKAGE_VERSION,
                                                      ^
scheduler.c:472:54: note: each undeclared identifier is reported only once for each function it appears in
scheduler.c:486:37: error: ‘KEEPALIVED_CONFIGURE_OPTIONS’ undeclared (first use in this function)
    log_options("configure options", KEEPALIVED_CONFIGURE_OPTIONS, 2);
                                     ^
scheduler.c:487:34: error: ‘CONFIGURATION_OPTIONS’ undeclared (first use in this function)
    log_options("Config options", CONFIGURATION_OPTIONS, 2);
                                  ^
In file included from notify.c:41:0:
utils.h:52:0: warning: "VERSION_STRING" redefined [enabled by default]
 #define VERSION_STRING  PACKAGE_NAME " v" PACKAGE_VERSION " (" GIT_DATE ")"
 ^
scheduler.c:488:34: error: ‘SYSTEM_OPTIONS’ undeclared (first use in this function)
    log_options("System options", SYSTEM_OPTIONS, 2);
                                  ^
In file included from notify.c:23:0:
config.h:27:0: note: this is the location of the previous definition
 #define VERSION_STRING PROG" v1.2.13 (08/02,2020)\n"
 ^
In file included from notify.c:41:0:
utils.h:53:0: warning: "COPYRIGHT_STRING" redefined [enabled by default]
 #define COPYRIGHT_STRING "Copyright(C) 2001-" GIT_YEAR " Alexandre Cassen, <acassen@gmail.com>"
 ^
In file included from notify.c:23:0:
config.h:28:0: note: this is the location of the previous definition
 #define COPYRIGHT_STRING "Copyright (C) 2001-2012 Alexandre Cassen, <acassen@gmail.com>"
 ^
scheduler.c: In function ‘thread_make_master’:
scheduler.c:674:36: error: ‘F_SETFD’ undeclared (first use in this function)
  if (set_sock_flags(new->epoll_fd, F_SETFD, FD_CLOEXEC))
                                    ^
scheduler.c:674:45: error: ‘FD_CLOEXEC’ undeclared (first use in this function)
  if (set_sock_flags(new->epoll_fd, F_SETFD, FD_CLOEXEC))
                                             ^
notify.c: In function ‘notify_fifo_exec’:
notify.c:202:45: error: ‘environ’ undeclared (first use in this function)
   execve(script->args[0], args.execve_args, environ);}

**Comment by azura27** [comment]
@andrewhit
Hi， when reproducing this PR, the compiling is stopped for depencies ERROR, could you pls take some time to RE-compile this PR and provide the system info, Thanks a lot~~ the compiling Error are showed below:
The comiling is done on the branch "dpvs-bug-17" of your repository
{/usr/include/bits/socket_type.h:51:0: note: this is the location of the previous definition
#define SOCK_CLOEXEC SOCK_CLOEXEC
^
scheduler.c: In function ‘report_child_status’:
scheduler.c:472:54: error: ‘PACKAGE_VERSION’ undeclared (first use in this function)
log_message(LOG_INFO, " Source version %s %s%s", PACKAGE_VERSION,
^
scheduler.c:472:54: note: each undeclared identifier is reported only once for each function it appears in
scheduler.c:486:37: error: ‘KEEPALIVED_CONFIGURE_OPTIONS’ undeclared (first use in this function)
log_options("configure options", KEEPALIVED_CONFIGURE_OPTIONS, 2);
^
scheduler.c:487:34: error: ‘CONFIGURATION_OPTIONS’ undeclared (first use in this function)
log_options("Config options", CONFIGURATION_OPTIONS, 2);
^
In file included from notify.c:41:0:
utils.h:52:0: warning: "VERSION_STRING" redefined [enabled by default]
#define VERSION_STRING PACKAGE_NAME " v" PACKAGE_VERSION " (" GIT_DATE ")"
^
scheduler.c:488:34: error: ‘SYSTEM_OPTIONS’ undeclared (first use in this function)
log_options("System options", SYSTEM_OPTIONS, 2);
^
In file included from notify.c:23:0:
config.h:27:0: note: this is the location of the previous definition
#define VERSION_STRING PROG" v1.2.13 (08/02,2020)\n"
^
In file included from notify.c:41:0:
utils.h:53:0: warning: "COPYRIGHT_STRING" redefined [enabled by default]
#define COPYRIGHT_STRING "Copyright(C) 2001-" GIT_YEAR " Alexandre Cassen, acassen@gmail.com"
^
In file included from notify.c:23:0:
config.h:28:0: note: this is the location of the previous definition
#define COPYRIGHT_STRING "Copyright (C) 2001-2012 Alexandre Cassen, acassen@gmail.com"
^
scheduler.c: In function ‘thread_make_master’:
scheduler.c:674:36: error: ‘F_SETFD’ undeclared (first use in this function)
if (set_sock_flags(new->epoll_fd, F_SETFD, FD_CLOEXEC))
^
scheduler.c:674:45: error: ‘FD_CLOEXEC’ undeclared (first use in this function)
if (set_sock_flags(new->epoll_fd, F_SETFD, FD_CLOEXEC))
^
notify.c: In function ‘notify_fifo_exec’:
notify.c:202:45: error: ‘environ’ undeclared (first use in this function)
execve(script->args[0], args.execve_args, environ);}

**Comment by andrewhit** [comment]
Okay. I will check it again.

**Comment by andrewhit** [comment]
> Okay. I will check it again.

@azura27 I just pushed the latest patch by force and please verify the commit, `from 1f4f719 to 757342d 1 `.

And the below image can be generated accordingly. If you meet any issue, please let me know.

```
zhuangyan@devbox-zhuangyan:~/my-dpvs$ git br
  DPVS-1.6-LTS
  DPVS-1.7-LTS
  devel
* dpvs-bug-17
  dpvs-bug-22
  dpvs-bug-26
  master
zhuangyan@devbox-zhuangyan:~/my-dpvs$ ll bin
total 3.8M
-rwxr--r-- 1 zhuangyan zhuangyan 199K Aug  5 22:17 dpip*
-rwxr--r-- 1 zhuangyan zhuangyan 176K Aug  5 22:17 ipvsadm*
-rwxr--r-- 1 zhuangyan zhuangyan 521K Aug  5 22:17 keepalived*
-rwxr--r-- 1 zhuangyan zhuangyan 2.9M Aug  5 22:17 dpvs*
```

**Comment by azura27** [comment]
@andrewhit 
Hello, this module has been compiled success. After review the code, this is to split the origin  conn Module into two PARTs. In our production environ, this splition do not have improvement on the usage, So we may not need this. Thaks again

**Pull request closed without merging**
