### PR TITLE
Correct ret value of netlink_route

### PR DESCRIPTION
**Pull request by royhunter**
fix keepalived static route reload issue

### CODE REVIEW

**Comment by ywc689** [comment]
"fix keepalived static route reload issue":  What's the reload issue? Could you please describe the issue in detail?  Thanks.

**Comment by royhunter** [comment]
The issue is:
After delete one entry of static_routes in keepalived.conf, then use "dpip route show" to show routes, this route still shown from command

**Comment by ywc689** [comment]
Could you please give a keepalived.conf to reproduce the preblem? Thanks.

**Comment by royhunter** [comment]
> Could you please give a keepalived.conf to reproduce the preblem? Thanks.

1. in keepalived.conf, add one entry of static routes:
static_routes {
    ...
    0.0.0.0/0 via 192.168.100.1 dev eth1
}

2. use "dpip route show" show this static route
.....
inet 0.0.0.0/0 via 192.168.1.1 src 0.0.0.0 dev eth1 mtu 1500 tos 0 scope global metric 0 proto auto ==> here!!

3. remove it from keepalived.conf, then use "dpip route show", route is still there:
inet 0.0.0.0/0 via 192.168.1.1 src 0.0.0.0 dev eth1 mtu 1500 tos 0 scope global metric 0 proto auto

**Pull request merged**
